- hosts: jenkins
  become: true
  tasks:
  - name: jenkins user
    user:
      name: jenkins
      groups: 
      - docker
      append: true
      shell: /bin/bash
  - name: install private key
    copy:
      src: ~/.ssh/ansible_id_rsa
      dest: /home/jenkins/.ssh/id_rsa
      owner: jenkins
      group: jenkins
      mode: u=rw,g=,o=
  - name: install java
    apt:
      name: openjdk-8-jdk
      state: latest
  - name: jenkins gpg key
    apt_key:
      url: "https://pkg.jenkins.io/debian/jenkins.io.key"
      state: present
  - name: jenkins apt repo
    apt_repository:
      repo: "deb http://pkg.jenkins.io/debian-stable binary/"
      state: present
  - name: jenkins install
    apt:
      name: jenkins
      state: latest
      update_cache: true
  - name: jenkins service
    service:
      name: jenkins
      state: started
  - name: "python pip"
    apt:
      name: python-pip
      state: latest
      update_cache: true
  - name: "docker sdk"
    pip:
     name: docker-py
  - name: "docker registry container"
    docker_container:
      name: registry
      image: registry
      ports:
      - "5000:5000"
  - name: "insecure registries"
    copy:
      src: ./daemon.json
      dest: /etc/docker/daemon.json
  - name: "reload docker"
    service:
      name: docker
      state: reloaded



